language: java
sudo: false
jdk:
- openjdk8
install: true
script: "./travis.sh"
env:
  global:
    - BUILD_SNAPSHOTS_BRANCH=travis
    - ARTIFACTORY_URL=https://mifos.jfrog.io/mifos
    - ARTIFACTORY_USER=travis-ci
    - secure: "owU7ZwpCzItH/bNYEWL6mKzAcwWITfCVaeU1aqgk8p4sudFxC2Fxl4Drb9wC6Qftn+PAlJmf3eOFmwvGMDgdo9DuuAVM2pkCSvJuHK6sYFdLTjmNWTiUwvk2vi1jLx03FQBbFnTE0Tik+xP/171B33WXAjsAXHqF6GXk0GSxeT3NMgGZN7A/yNDrtn/Lyz2iaOqG5PRv+epjz4WK85jjmikTmdrqrThRvlLFrAOR2/Cff4SkjP9fx3UVs42hVMIzkyokLY3eOXGkQg3pOt0z+X8VK7cfra9pha/vLoipQkdKCgz8wwXGdYV7yJenWH3tqnzwsgM/Khsj4b/6uJQyR3plBIpqs/ZtjDO0uXvgqSK1h+q0GAWz9VbX31C4RAex2Ytow/YnY5a3iXgttofIPObAJ62/NvQhNTw4l0+4tn3wDVKDTcdDGqNvzJLovsvFJEdDYJ8K9DDc+4Z+xNefiYtogaSBAZLGeo8L8RvX4L9MkqKBLu627SUl9Gr3EYn5t0z3Shikf+xEr7FcxU8KxC8jaK6tZ2cCxr+vssBRevPFKd+1ivbrg1tZJsiuRe2KqAkm/unmtzRRFtuRw2iaGBYtzPzyeHbOtOigmlxS52qf1NkD5gpNdOz7l1RJCNppnKFVcoqw9ezYNqsAuCFcgGL8lNx4KRmOyFDblm8OugQ="

