language: java
sudo: false
jdk:
- openjdk8
install: true
script: "./travis.sh"
env:
  global:
  - ARTIFACTORY_URL=https://mifos.jfrog.io/mifos
  - secure: b/y76p3PWEkgpsvARxSTxCs2+6jWnqp1iPttavslmOryXtc5DlMwZTqXAxUaSHUoGlhvFJjZbgaTrIsJy9idkgwHik+m4ftWpTTabuWiyOGuvQnJHvYzdTb0/Vc1OyZmRHyENyLWHqx9B7O8M71DuQT0jKFOBDt4n27RBw++hPdG1KBE6M3EricmWQvSd0lWSuX7pVUni7ag2t7+EcACSYnhXOp/895ar7zvVRIzGtsWYnVjSrWY0hgDk+2exhRTiNegfPjENnypGGpDm7NVReMRUrFJTqKhq8hGX1s255Lled8qjc6/aGeeGRGURvxzTp/idO1Y2+JX4ABqOa7PUnaG3HdDN+44lM9p80VZKRlV64Bm145uSTYRMKwhy5d82bknLS6C270U+T0b+f6JzkHMKes/+xqYdoQ2U2o6igBJnXFQRVRTvi58FmOS4a7efDiKA9nbt7/YQ4Z57CrXs4G2PBUZ897M42i7btOJK3txvYr9GhZ8lBN/8MGKXMySxQ37QhpxoNZSXSpjYsUS6zlx1pm08JbpcPWkwgtyTn/0C5lxu/dTAkY5nLRmsoXYAREvOZqM+ton55JEI5qMWpKZUOOcUaJra+iLzvQ1lP2Wf+gA6kpy1+ISBODtXCOmteE8DL3kPGFtdKMGgqkSLuHh6kKTnBIWFfG1OSVHuBA=
  - secure: eSippNzfNod9692BdaMezL/3N/dmIGv/0/PrZMSSo4QXN/j/tMy5DUBgP/rvkbiIc8u0sEV9clNuUp2XCWv8IuOoKf1hu5PJxTcHPyMh4ldbcjHfIpHAlg9Wh5q1wKH3MAPL7LYdi6L0K87cItv7YjJeYRehHwfDhlnBv0p0LqgIgiupPNCW6Nh8QyJuepTRd8bp+B4NTFShd6xGVD+StPFkn8Q1qT+9DI+dqih9zCtKExIpirP22rVrFFVf8Md9hEuGZlfT8FQiTJDpeXN1o+GVa0kv1HDNhIqqQaMYeqxTqQ/WLCbtXV9WoPC+LS4JXwCZtA3QCsHnKsKNqJATr59a8QJOdo6FNCNNIoYbZ+0YVGiqHdkZzxgbDDW0xTC97Sfkwt5e0iK39nPQQGwAO3r+ZphR6dY95Opjh52tBV9LOMBJd5Tt7mQ8NBPR2RQUmYzKFacyKCQuMBKUW5rtOZdG9WgT9l2iLjBzunOCg3FBdm1Kb8pi3HWV+PnfWvWZT6rO1tPjR5IRUXzmFzIdTai4l8cB9EILVAt86fETyyuODjuVNz01xvu0vS1+ydbXWw2xA+eGkmjeirwx01Se6TnjQUz8rqSVPQgoljmRcciGUeoLVCpGiUCOOj3r5BqDns4eU06n0ofrMjXpB2HQU9enTdHjxdD7ZTDz0UsOCLQ=

