language: java
sudo: false
jdk:
- openjdk8
install: true
script: "./travis.sh"
env:
  global:
  - ARTIFACTORY_URL=https://mifos.jfrog.io/mifos
  - secure: "MnRGD74JoEBE6T+eGxuV9Rsb0y/dWDx4wLBVfdB5jiKFPnT85LOfZMOXXlh0PqOBk+9k/SCOK/8UswMJ/k1Ewiy0qMm1dzgQFopmCi14jh/zXbFci4IaCUIsPROJ+yOSLT6QzeAi+Jk31+1Df4F4D51luewrcrYydPuAl68OE1HpCRkPjolPkQ/dDOOyozXT+S69az8thfhsrlSCr22ktnKO/tZ6aPwmjR9Kq6GjypazTjfB2l1/+8lfUxi5gexMQ2oBSEArWYl3q/Bdz5yfbXc/EVkFrivRGVTk5WfQKP3um0YGQ8eMBFMzlK6PR6TDXLxWdgUCpyn6ZwaD7GfpYCkzQQTe2PoI4qj6Z/dcxzoYf1QPGmbAOe0VmTcZiXrm3IMlsKMjkKzvM3IKO+qtBK87B8/+NMFrs53w4kL876LH49XzFNhL5pitVbb44wHH30zeoSgORWC8dVSjRjXlNTtc1vfPIQ0qIdsV8LoiNBV6mg6bZJ41GcuEAqG5a2ylmRrxkSZCRx23A7aP9uojXp/b4Fshgbm8C+LQ/3qtd38MeUDAFLVZixWBDCbToOcjRFjiGw9WhTisRfpCHk0ZaFRzxr9U2W53lRrTwML5/s6fXWo6oAqTYP0mOWpASwc821kk6m8iAt9zImICLZwGy93gKYA+dCRAJuuqQ+JAvUg="
  - secure: "owU7ZwpCzItH/bNYEWL6mKzAcwWITfCVaeU1aqgk8p4sudFxC2Fxl4Drb9wC6Qftn+PAlJmf3eOFmwvGMDgdo9DuuAVM2pkCSvJuHK6sYFdLTjmNWTiUwvk2vi1jLx03FQBbFnTE0Tik+xP/171B33WXAjsAXHqF6GXk0GSxeT3NMgGZN7A/yNDrtn/Lyz2iaOqG5PRv+epjz4WK85jjmikTmdrqrThRvlLFrAOR2/Cff4SkjP9fx3UVs42hVMIzkyokLY3eOXGkQg3pOt0z+X8VK7cfra9pha/vLoipQkdKCgz8wwXGdYV7yJenWH3tqnzwsgM/Khsj4b/6uJQyR3plBIpqs/ZtjDO0uXvgqSK1h+q0GAWz9VbX31C4RAex2Ytow/YnY5a3iXgttofIPObAJ62/NvQhNTw4l0+4tn3wDVKDTcdDGqNvzJLovsvFJEdDYJ8K9DDc+4Z+xNefiYtogaSBAZLGeo8L8RvX4L9MkqKBLu627SUl9Gr3EYn5t0z3Shikf+xEr7FcxU8KxC8jaK6tZ2cCxr+vssBRevPFKd+1ivbrg1tZJsiuRe2KqAkm/unmtzRRFtuRw2iaGBYtzPzyeHbOtOigmlxS52qf1NkD5gpNdOz7l1RJCNppnKFVcoqw9ezYNqsAuCFcgGL8lNx4KRmOyFDblm8OugQ="

